### ISSUE TITLE
[REQUEST] Readme for how to use it

### ISSUE THREAD

**Issue by ghost** [drakeee/altv-lua-module#5]
it would  be nice if there are any instructions on how to use it for altv :D

**Comment by drakeee** [comment]
If you go into the Pinned Messsages on Discord channel (#lua) you can see a full example converted a script from JS to Lua.
https://github.com/drakeee/altv-quickstart-lua

Also you can use the wiki as well (it's not completed yet but i'm working on it)
https://wiki.itsdrake.com/index.php/Main_Page

(the structure and function names are similar to JS)

If you have questions feel free to ask on [alt:V's Discord](https://discord.gg/q3zUUEC) channel (#lua).
